### PR TITLE
use adapter.js

### PR DESCRIPTION
**Pull request by fippo**
moar adapter. h/t @legastero @xdumaine :-)

### CODE REVIEW

**Comment by fippo** [comment]
published as 1.3.0

**Comment by xdumaine** [comment]
Seem to be getting Reference Errors in unsupported browsers in LocalMedia now. Might be an issue on my end, but thought I'd mention it here in case you knew of anything.

**Comment by xdumaine** [comment]
FYI https://github.com/webrtc/adapter/pull/64

**Comment by fippo** [comment]
let's work around this internally for now... see also my PR #63

**Pull request merged**
